GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "admin_password"
DB_SERVER_NAME = "agentdb456.database.windows.net"
DB_NAME = "compliance_db"
DB_USERNAME = "agent123" # Your full Entra ID UPN
DB_PASSWORD = "MLa3EQTcJ#2c8AL"
DB_PORT = 1433
