GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "admin_password"

# Database Connection Settings
DB_SERVER_NAME = "rahulsalpard.database.windows.net"
DB_NAME = "rahulsalpard"
DB_USERNAME = "agent123"
DB_PASSWORD = "Aug@2025"
DB_PORT = 1433

# Alternative key names for compatibility
DB_SERVER = "rahulsalpard.database.windows.net"

# Application Settings (optional)
APP_ENV = "production"
DEBUG = false

# Connection Pool Settings (optional)
CONNECTION_TIMEOUT = 30
LOGIN_TIMEOUT = 30
POOL_SIZE = 5
MAX_OVERFLOW = 10

# Security Settings (optional)
ENCRYPT = true
TRUST_SERVER_CERTIFICATE = false